FROM openjdk:8-jdk
MAINTAINER Mayank Koli "mayank.c.koli@gmail.com"
ENV GRADLE_VERSION 4.0
RUN cd /usr/lib \
 && curl -fl https://downloads.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -o gradle-bin.zip \
 && unzip "gradle-bin.zip" \
 && ln -s "/usr/lib/gradle-${GRADLE_VERSION}/bin/gradle" /usr/bin/gradle \
 && rm "gradle-bin.zip"
ENV GRADLE_HOME /usr/lib/gradle
ENV PATH $PATH:$GRADLE_HOME/bin
RUN mkdir /app
WORKDIR /app
RUN git clone https://github.com/mavericks-consulting/payment-service.git
WORKDIR /app/payment-service/
RUN gradle build
#CMD [ "gradle", "bootrun" ]

