FROM docker.io/manukoli1986/nodejs8:nodejs8
MAINTAINER Mayank Koli "mayank.c.koli@gmail.com"
RUN mkdir -p /app
RUN git clone https://github.com/mavericks-consulting/product-service.git
WORKDIR /app/product-service/
RUN npm install
ENV PORT=9000
